desc: Macro controller
author: The REAPER Blog
version: 1.0
provides: ReaperBlog_Macro Controller/New file 1.jsfx
about: Dummy controls to use with Parameter link/modulation

/**
 * Changelog:
 * v1.0 (2018-03-14)
  + Initial Release
 */
 
 desc:Macro Controller


slider1:50<0, 100, 1>Macro 1
slider3:50<0, 100, 1>Macro 2
slider5:50<0, 100, 1>Macro 3
slider7:50<0, 100, 1>Macro 4
slider9:50<0, 100, 1>Macro 5

